TURN_PLAYER = "Player"
TURN_CAT = "Cat"

TILE_EMPTY = 0
TILE_TRAP = -1
TILE_CAT = 1

MODE_GREEDY = "greedy"
MODE_FROZEN = "frozen"
MODE_LEARNING = "learning"
MODE_MANUAL = "manual"

DISTANCE_UNREACHABLE = 999999999
NEGATIVE_INF = -999999999
